export const stacks = [
  { id: "capacitor", label: "Capacitor" },
  { id: "webview", label: "WebView" },
  { id: "react-native", label: "React Native" },
  { id: "pwa", label: "PWA shell" },
  { id: "other", label: "Other" },
] as const;

export type StackId = (typeof stacks)[number]["id"];

export type RiskLevel = "HIGH" | "MED" | "LOW";

export type FlagResult = {
  level: RiskLevel;
  score: number;
  reasons: string[];
};

export type PrecheckInput = {
  name: string;
  description: string;
  stack: StackId;
  features: [string, string, string];
};

export type PrecheckResult = {
  overall: RiskLevel;
  blurb: string;
  flags: {
    "4.2": FlagResult;
    "4.3": FlagResult;
    metadata: FlagResult;
  };
  featureReads: { text: string; signal: "high" | "medium" | "low" }[];
};

const HIGH_SIGNAL =
  /\b(share sheet|uiactivity|widget(?:kit)?|live activit|app intent|spotlight|storekit|in-?app purchase|iap\b|face id|touch id|passkeys?|biometric|apns|native tabs?|document picker|files app|healthkit|nfc|callkit|siri|apple watch|lock screen|home screen widget|keychain|app clip)\b/i;

const MEDIUM_SIGNAL =
  /\b(camera|photos? picker|haptics?|push|notifications?|offline|geolocation|gps|contacts|local notifications?|universal links?|deep links?|background refresh|biometric|file picker|clipboard|haptic)\b/i;

const LOW_SIGNAL =
  /\b(splash|launch screen|app icon|icons?|capacitor|cordova|ionic|plugin|pull[- ]to[- ]refresh|settings page|website|webview|html|css|cookie banner|safari|xcode|swiftui|we use native|native plugins?)\b/i;

const CLONE =
  /\b(clone|reskin|template|like uber|like instagram|like tiktok|like chatgpt|like notion|same as|copy of|ai wrapper|generated by lovable|bolt\.new|v0\.dev)\b/i;

const GENERIC_NAME =
  /^(ai[- ]?)?(my[- ]?)?(super[- ]?)?(todo|notes?|chat|gpt|assistant|tracker|weather|flashlight|qr|scanner|calculator|timer|habits?|journal|wrapper|ai app|chatbot)\b/i;

const PLACEHOLDER =
  /\b(lorem|ipsum|todo\b|tbd\b|coming soon|placeholder|asdf|test app|lorem ipsum)\b/i;

function clamp(n: number) {
  return Math.max(0, Math.min(100, Math.round(n)));
}

function levelFrom(score: number): RiskLevel {
  if (score >= 62) return "HIGH";
  if (score >= 38) return "MED";
  return "LOW";
}

export function isStackId(value: string): value is StackId {
  return stacks.some((item) => item.id === value);
}

export function classifyFeature(text: string): "high" | "medium" | "low" {
  const value = text.trim();
  if (!value) return "low";
  if (HIGH_SIGNAL.test(value)) return "high";
  if (LOW_SIGNAL.test(value)) return "low";
  if (MEDIUM_SIGNAL.test(value)) return "medium";
  return "low";
}

function stack42Base(stack: StackId, blob: string): { score: number; reason: string } {
  if (stack === "capacitor") {
    return {
      score: 78,
      reason:
        "Capacitor binaries are reviewed as wrappers until native surfaces are obvious on first tap.",
    };
  }
  if (stack === "webview") {
    return {
      score: 82,
      reason:
        "A WebView shell is the textbook 4.2 pattern: website in a frame, splash, done.",
    };
  }
  if (stack === "pwa") {
    return {
      score: 80,
      reason:
        "A PWA shell usually is the website. 4.2 asks for more than add-to-home-screen.",
    };
  }
  if (stack === "react-native" && /webview|capacitor|pwa|website/i.test(blob)) {
    return {
      score: 70,
      reason:
        "React Native plus WebView/website language still reads as a wrapper to Review.",
    };
  }
  if (stack === "react-native") {
    return {
      score: 44,
      reason:
        "React Native can be a real native app — 4.2 risk depends on whether the job is native or a site.",
    };
  }
  return {
    score: 32,
    reason:
      "Stack isn’t an automatic wrapper tell. Risk still rises if features look like a website.",
  };
}

export function scorePrecheck(input: PrecheckInput): PrecheckResult {
  const name = input.name.trim();
  const description = input.description.trim();
  const features = input.features.map((item) => item.trim()) as [
    string,
    string,
    string,
  ];
  const blob = `${name} ${description} ${features.join(" ")}`;

  const featureReads = features.map((text) => ({
    text,
    signal: classifyFeature(text),
  }));

  const highCount = featureReads.filter((item) => item.signal === "high").length;
  const medCount = featureReads.filter((item) => item.signal === "medium").length;
  const lowCount = featureReads.filter((item) => item.signal === "low").length;

  const base = stack42Base(input.stack, blob);
  let score42 = base.score;
  const reasons42 = [base.reason];

  score42 -= highCount * 18;
  score42 -= medCount * 8;
  score42 += lowCount * 8;

  if (highCount) {
    reasons42.push(
      `${highCount} claimed feature${highCount === 1 ? "" : "s"} look high-signal (system UI Review can screenshot).`,
    );
  }
  if (lowCount) {
    reasons42.push(
      `${lowCount} claimed feature${lowCount === 1 ? "" : "s"} are low-signal (splash, plugins, “we use Capacitor”).`,
    );
  }
  if (
    /website|wrapper|same as (the )?web|marketing site|lovable|bolt|v0\b/i.test(
      description,
    )
  ) {
    score42 += 12;
    reasons42.push(
      "The one-liner still sounds like the website, a generator export, or a wrapper.",
    );
  }
  if (highCount === 0 && (input.stack === "capacitor" || input.stack === "webview" || input.stack === "pwa")) {
    score42 = Math.max(score42, 72);
    reasons42.push(
      "No tappable native evidence listed. A better letter will not beat 4.2 on this binary.",
    );
  } else if (highCount === 0 && input.stack === "react-native") {
    score42 = Math.max(score42, 48);
    reasons42.push(
      "React Native without a system UI (share sheet, widget, Face ID, APNs screenshot) still looks optional to 4.2.",
    );
  }

  score42 = clamp(score42);

  let score43 = 24;
  const reasons43: string[] = [];
  if (CLONE.test(blob)) {
    score43 += 40;
    reasons43.push(
      "Clone / template / “like App X” language is a 4.3 spam tell, even with native chrome.",
    );
  }
  if (GENERIC_NAME.test(name) || /^(untitled|my app|test)\b/i.test(name)) {
    score43 += 22;
    reasons43.push(
      `“${name}” reads like a generic utility or template listing, not a specific job.`,
    );
  }
  if (features.every((item) => classifyFeature(item) !== "high") && description.length < 40) {
    score43 += 16;
    reasons43.push(
      "Short generic description plus generic features looks like a farm app.",
    );
  }
  if (/(lovable|bolt|v0|cursor export|same card layout)/i.test(blob)) {
    score43 += 14;
    reasons43.push(
      "Generator / export tells (Lovable, Bolt, v0, identical cards) show up in 4.3 clusters.",
    );
  }
  if (reasons43.length === 0) {
    reasons43.push(
      "No obvious clone/template tell in the name or one-liner. 4.3 is quieter than 4.2 here.",
    );
  }
  score43 = clamp(score43);

  let scoreMeta = 22;
  const reasonsMeta: string[] = [];
  if (PLACEHOLDER.test(blob)) {
    scoreMeta += 40;
    reasonsMeta.push(
      "Placeholder / lorem / “coming soon” copy is a 2.3 metadata mismatch waiting to happen.",
    );
  }
  if (description.length < 24) {
    scoreMeta += 18;
    reasonsMeta.push(
      "One-liner is too thin. Listings with vague copy often ship screenshots that don’t match the binary.",
    );
  }
  if (
    /best |#1 |ai-powered|chatgpt-powered|keyword/i.test(`${name} ${description}`)
  ) {
    scoreMeta += 16;
    reasonsMeta.push(
      "Keyword-y or “AI-powered” claims get checked against what’s actually in the binary.",
    );
  }
  if (
    /web app|website|ios shell|wrapper|same site/i.test(description) &&
    input.stack !== "other"
  ) {
    scoreMeta += 20;
    reasonsMeta.push(
      "If the product is still the website, screenshots and the binary will disagree — that’s 2.3 as well as 4.2.",
    );
  }
  if (reasonsMeta.length === 0) {
    reasonsMeta.push(
      "No placeholder-copy tell. Metadata risk stays tied to whether screenshots match the binary.",
    );
  }
  scoreMeta = clamp(scoreMeta);

  const flags = {
    "4.2": {
      level: levelFrom(score42),
      score: score42,
      reasons: reasons42.slice(0, 3),
    },
    "4.3": {
      level: levelFrom(score43),
      score: score43,
      reasons: reasons43.slice(0, 3),
    },
    metadata: {
      level: levelFrom(scoreMeta),
      score: scoreMeta,
      reasons: reasonsMeta.slice(0, 3),
    },
  };

  const overallScore = Math.max(
    score42,
    Math.round(score42 * 0.7 + score43 * 0.2 + scoreMeta * 0.1),
  );
  const overall = levelFrom(overallScore);

  const blurb =
    overall === "HIGH"
      ? "Review is likely to see a website in a frame — not an iOS app worth a listing."
      : overall === "MED"
        ? "Not an automatic bounce, but 4.2/4.3 still have an easy screenshot against you."
        : "Wrapper tells are quieter. You still need evidence, not a pep talk, on resubmit.";

  return { overall, blurb, flags, featureReads };
}

export function toCheckQuery(input: PrecheckInput) {
  const params = new URLSearchParams();
  params.set("n", input.name.trim());
  params.set("s", input.stack);
  params.set("d", input.description.trim());
  params.set("f1", input.features[0].trim());
  params.set("f2", input.features[1].trim());
  params.set("f3", input.features[2].trim());
  return params.toString();
}

export function parseCheckInput(
  source: URLSearchParams | Record<string, string | string[] | undefined>,
): PrecheckInput | null {
  const read = (key: string) => {
    if (source instanceof URLSearchParams) return source.get(key) ?? "";
    const value = source[key];
    return Array.isArray(value) ? (value[0] ?? "") : (value ?? "");
  };

  const name = read("n").trim();
  const description = read("d").trim();
  const stack = read("s").trim();
  const features: [string, string, string] = [
    read("f1").trim(),
    read("f2").trim(),
    read("f3").trim(),
  ];

  if (!name || !description || !isStackId(stack)) return null;
  if (!features[0] || !features[1] || !features[2]) return null;

  return { name, description, stack, features };
}

export const demoHigh: PrecheckInput = {
  name: "FluxNotes",
  description: "Our web app in an iOS shell — same site, nicer icon.",
  stack: "capacitor",
  features: ["Splash screen", "Pull to refresh", "Capacitor plugins"],
};

export const demoMed: PrecheckInput = {
  name: "Harbor Log",
  description: "Field notes for marina staff, with a camera capture inbox.",
  stack: "react-native",
  features: ["Camera picker", "Push notifications", "Offline list"],
};

export const demoLow: PrecheckInput = {
  name: "Harbor Log",
  description: "Shift log for marina dockhands — widgets on the home screen.",
  stack: "react-native",
  features: ["Home screen widget", "iOS share sheet", "Face ID lock"],
};
